### ISSUE TITLE
更改其他模型之后界面崩溃退出

### ISSUE THREAD

**Issue by Colorsu17** [zstar1003/yolov5_pyqt5#6]
只能运行up原始的模型，更换其他模型就用不了，显示崩溃，如何将其修改为能够运行加载检测任何模型的界面？即使我更换了模型或者数据都不会崩溃，都能够正常运行

**Comment by zstar1003** [comment]
不可能运行任何模型，如有其它模型需求，可修改后端代码进行相应适配

**Comment by Colorsu17** [comment]
> 不可能运行任何模型，如有其它模型需求，可修改后端代码进行相应适配

想请教一下，不能运行其他模型是什么原因？（比如能运行up的，但是不能运行yolov5s的模型），按道理，除了模型结构可能有些差异之外跑的东西应该都差不多啊。也去尝试修改了一下，但是还不行 #

**Comment by Colorsu17** [comment]
up你好，我在你的原始界面的基础上直接加载我的模型，发现直接崩溃，然后改了好一段时间，发现还是不能正常运行😰。我的模型是yolov5s,然后在v5s的基础上做了修改，加了注意力机制，然后训练出了这两个模型，yolov5_CA,yolov5_SCConv。然后界面是跑不了，想请教一下，如果要修改，是需要改哪些具体的地方
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月15日 20:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zstar1003/yolov5_pyqt5] 更改其他模型之后界面崩溃退出 (Issue #6) |

不可能运行任何模型，如有其它模型需求，可修改后端代码进行相应适配

**Comment by zstar1003** [comment]
yolo相关模型基本支持，建议提供具体报错信息，以便排查问题

**Comment by Colorsu17** [comment]
报错如下：Traceback (most recent call last):
 File "h:/A_yolo/yolov5_pyqt5/main.py", line 269, in run
   detect.run(source=self.file_path, weights=self.model_path[0], show_label=self.label, save_img=True)
 File "D:\development\Anaconda\envs\yolov5-7.0\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
   return func(*args, **kwargs)
 File "h:\A_yolo\yolov5_pyqt5\detect.py", line 59, in run
   model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
 File "h:\A_yolo\yolov5_pyqt5\models\common.py", line 361, in __init__
   model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
 File "h:\A_yolo\yolov5_pyqt5\models\experimental.py", line 79, in attempt_load    
 File "h:\A_yolo\yolov5_pyqt5\models\experimental.py", line 79, in attempt_load    
   ckpt = torch.load(attempt_download(w), map_location='cpu')  # load
 File "D:\development\Anaconda\envs\yolov5-7.0\lib\site-packages\torch\serialization.py", line 607, in load
   return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)  
 File "D:\development\Anaconda\envs\yolov5-7.0\lib\site-packages\torch\serialization.py", line 882, in _load result = unpickler.load()
 File "D:\development\Anaconda\envs\yolov5-7.0\lib\site-packages\torch\serialization.py", line 875, in find_class return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'ScConv' on<module 'models.common' from 'h:\\A_yolo\\yolov5_pyqt5\\models\\common.py'>。。是因为common.py文件中没有把结构层放上去吗？


在2024年12月15日 ***@***.***> 写道：

yolo相关模型基本支持，建议提供具体报错信息，以便排查问题

**Comment by zstar1003** [comment]
是的，改进网络需要把ScConv等额外的自创模块添加到相应位置

**Comment by Colorsu17** [comment]
感谢回复，再去尝试一下，非常感谢
在2024年12月15日 ***@***.***> 写道：

是的，改进网络需要把ScConv等额外的自创模块添加到相应位置
